export const containsAllergen = (aiDescription: string, allergen: string):boolean => {
  // strip uppercase
  let sanitizedAiDescription = aiDescription.toLowerCase()
  let sanitizedAllergen = allergen.toLowerCase()
  // strips , . ( ) [ ] - _ * " ' { } ? ! + = ^ & % $ # @ ; : \ / ` ~ and whitespace
  const specialCharacterRegex = /[,.()\[\]-_*"'{}?!+=^&%$#@;:\\/`~\s]/g
  sanitizedAiDescription = sanitizedAiDescription.replace(specialCharacterRegex, '')
  sanitizedAllergen = sanitizedAllergen.replace(specialCharacterRegex, '')

  return sanitizedAiDescription.includes(sanitizedAllergen)
}


// update this list with CAS / EC of the following:
//   https://ec.europa.eu/growth/tools-databases/cosing/
//     HEMA (spelling not exact)
//     CARBAMATE (spelling not exact)
// need CAS / EC of all the subingredients here too:
//   https://ec.europa.eu/growth/tools-databases/cosing/details/28313
//   https://ec.europa.eu/growth/tools-databases/cosing/details/28271

export const listOfAllergens:string[] = [
  "Carba Mix",
  "MDBGN (Methyldibromo glutaronitrile)",
  "Toluenesulfonamide formaldehyde resin",
  "Colophony",
  "2-Hydroxyethylmethacrylate",
  "Cobalt",
  "2-Bromo-2-nitropropane-1,3-diol",
  // Textiles
  "Neoprene",
  "Elastane",
  "Nylon",
  "Spandex",
  "Lycra",
  // Synonyms
  "chloroprene",
  "elastic",


  // Carba Mix (MX-06)
  "Carba Mix",
  "MX-06",
  // Synonyms
  "Carbamate",
  "Diphenylguanidine",
  "DPG",
  "Noccel D",
  "Sanceler D",
  "Zinc Dibutyldithiocarbamate",
  "Butasan",
  "Butazate",
  "Butazin",
  "Butyl Zimate",
  "Zinc Deithydithiocarbamate",
  "ZDC",
  "ZBC",
  "Nocceler BZ",
  "Soxinol",
  "Etazin",
  "Ethasan",
  "Ethazate",
  "Ethyl Zimate",
  "Nocceler EZ",
  "zinc bis(diethyldithiocarbamate)",
  "bis(N,N-dibutyldithiocarbamato)zinc",
  "carbamic acid dibutyldithio",
  "zinc complex",
  "zinc bis(dibutyldithiocarbamate)",
  "Zincdiethyldithiocarbamate",
  "diethyldithiocarbamic acid zinc salt",
  // Norsk
  "Karbamater",
  "Difenyloguanidin",
  "Sinkdibutylditiokarbamat",
  "Sinkdietylditiokarbamat",
  "Sinkbis(dietylditiokarbamat)",
  "bis(N,N-dibutylditiokarbamato)sink",
  "Karbaminsyre dibutylditio",
  "Sinkkompleks",
  "Sinkbis(dibutylditiokarbamat)",
  "Sinkdietylditiokarbamat",
  "Dietylditiokarbaminsyre, sinksalt",
  "Etyl Zimate",
  // EU
  "Urethane",
  "Maneb",
  "Pirimicarb",
  "ZINC BORATE",    
"  ZINC ASPARTATE",
"  ZINC CHLORIDE",
"  LACTOBACILLUS LAC/CALCIUM/PHOSPHOROUS/MAGNESIUM/ZINC FERMENT",
"  PORPHYRIDIUM/ZINC FERMENT",
"  ZINC ACETATE",
"  ZINC DIBUTYLDITHIOCARBAMATE",
"  ZINC GLUCONATE",
"  ZINC PCA",
"  ZINC GLUCOHEPTONATE",
"  ZINC LACTATE",
"  ZINC GLUTAMATE",
"  ZINC PENTADECENE TRICARBOXYLATE",
"  LACTOBACILLUS/MILK/MANGANESE/ZINC FERMENT LYSATE",
"  SODIUM ZINC HISTIDINE DITHIOOCTANAMIDE",
"  SODIUM ZINC CETYL PHOSPHATE",
"  ZINC SULFATE",
"  SACCHAROMYCES/ZINC/IRON/GERMANIUM/COPPER/MAGNESIUM/SILICON FERMENT",
"  ZINC ADENOSINE TRIPHOSPHATE",
"  ZINC ASCORBATE",
"  ZINC COCO-SULFATE",
"  ZINC COCETH SULFATE",
"  ZINC GLYCINATE",
"  ZINC CYSTEINATE",
"  ZINC MAGNESIUM ASPARTATE",
"  ZINC PICOLINATE",
"  ZINC THIOSALICYLATE",
"  ZINC SALICYLATE",
"  ZINC UNDECYLENOYL HYDROLYZED WHEAT PROTEIN",
"  SACCHAROMYCES/ZINC FERMENT",
"  ZINC CITRATE",
"  ZINC FORMALDEHYDE SULFOXYLATE",
"  ZINC HYDROLYZED COLLAGEN",
"  ZINC GLYCINATE SALICYLATE",
"  SODIUM ZINC TAURINE DITHIOOCTANAMIDE",
"  ZINC ASCORBATE HYDROXIDE",
"  ZINC NITRATE",
"  ZINC HYDROLYZED HYALURONATE",
  // EU norsk
  "Uretan",
  "Maneb",
  "Pirimikarab",
  "Sinkborat",
  "Sinkaspartat",
  "Sinkklorid",
  "Lactobacillus lac/Kalsium/Fosfor/Magnesium/Sink-ferment",
  "Porfyridium/Sink-ferment",
  "Sinkacetat",
  "Sinkdibutylditiokarbamat",
  "Sinkglukonat",
  "Sink PCA",
  "Sinkglukoheptonat",
  "Sinklaktat",
  "Sinkglutamat",
  "Sinkpentadekentrikarboksylat",
  "Lactobacillus/Melk/Mangan/Sink-ferment-lysat",
  "Natrium-sink-histidin-ditioktanamid",
  "Natrium-sink-cetylfosfat",
  "Sinksulfat",
  "Saccharomyces/Sink/Jern/Germanium/Kobber/Magnesium/Silikon-ferment",
  "Sinkadenosintrifosfat",
  "Sinkaskorbat",
  "Sinkkokosulfat",
  "Sinkkokettsulfat",
  "Sinkglysinat",
  "Sinkcysteinat",
  "Sinkmagnesiumaspartat",
  "Sinkpikolinate",
  "Sinktiosalisylat",
  "Sinksalisylat",
  "Sinkundecylenoylhydrolysert hveteprotein",
  "Saccharomyces/Sink-ferment",
  "Sinksitrat",
  "Sinkformaldehydsulfoxylat",
  "Sinkhydrolysert kollagen",
  "Sinkglysinat-salisylat",
  "Natrium-sink-taurin-ditioktanamid",
  "Sinkaskorbat-hydroksid",
  "Sinknitrat",
  "Sinkhydrolysert hyaluronat",
  // CAS
  " 102-06-7 ",
  // EC
  " 203-002-1 ",


  // MDBGN (Methyldibromo glutaronitrile) (D-049E)
  "MDBGN",
  "Methyldibromo glutaronitrile",
  "Méthyldibromo glutaronitrile",
  "D-049E",
  // Synonyms
  "2-Bromo-2",
  "dibromoglutaronitrile",
  "bromomethyl glutaronitrile",
  "bromomethyl pentanedinitrile",
  "Dibromo dicyanobutane",
  "1,2-Dibromo-2,4-dicyanobutane",
  "Dibromodicyanobutane",
  "Merquat 2200",
  "Phenoxyethanol",
  "Tektamer 38",
  "Bromothalonil",
  "Euxyl K400",
  "Metacide 38",
  // Norsk
  "Metyl-dibromoglutaronitril",
  "Bromometylglutaronitril",
  "Bromometylpentandinitril",
  "Dibromodicyanobutan",
  "1,2-Dibrom-2,4-dicyanobutan",
  "Dibromdicyanobutan",
  "Fenoksyetanol",
  "Bromotalonil",
  "Dibromoglutaronitril",
  // CAS
  "35691-65-7",
  "835913-41-2", 
  "122-99-6", 
  // EC
  "252-681-0",
  "204-589-7",
  

  // Toluenesulfonamide formaldehyde resin (T-010)
  "Toluenesulfonamide",
  "T-010",
  "formaldehyde resin",
  // Synonyms
  "Benzene sulfonamide",
  "4-methyl-polymer",
  "Mearlmaid TX-EPM-8-6",
  "Santolite MHP",
  "Santolite MS",
  "Tosylamide",
  // Norsk
  "Toluenesulfonamid",
  "Formaldehydharpiks",
  "Benzenesulfonamid",
  "4-metylpolymer",
  "Tosylamid/formaldehyd",
  "Tosylamidharpiks",
  // CAS
  " 70-55-3 ",
  "88-19-7",
  "80-39-7",
  "1077-56-1 ",
  " 25035-71-6 ",
  " 39277-28-6 ",
  // EC
  "200-741-1",
  "201-808-8 ",
  "201-275-1",
  "214-073-3 ",


  // 2-Bromo-2-nitropropane-1,3-diol (B-015B)
  "nitropropane",
  "3-diol",
  "B-015B",
  // Synyonyms
  "2-Nitro-2",
  "Bronidiol",
  "Bronocot",
  "Bronopol",
  "Bronosol",
  "Bronotak",
  "HSDB 7195",
  "Lexgard bronopol",
  "NSC 141021",
  "Onyxide 500",
  "nitrotrimethyleneglycol",
  "b-Bromo-b",
  "myacide",
  "bromo-2-nitro",
  "bromo-1-nitro",
  "nitro-2-bromo",
  "nitro-1-bromo",
  // Norsk
  "Nitropropan",
  "Nitrotrimetylenglykol",
  // CAS
  " 52-51-7 ", 
  // EC
  " 200-143-0 ", 


  // Colophony (C-020)
  "Colophony",
  "C-020",
  // Synonyms
  "Disproportionated rosin",
  "Disproportionated resin",
  "Gum resin",
  "Wood resin",
  "Pine resin",
  "Pine gum",
  "Wood Gum",
  "Colophony",
  "Abietic alcohol",
  "Abietyl alcohol",
  "Colophonium",
  "Rosin",
  "Tall oil",
  "Abietic acid",
  "Abietic Alcohol",
  "Methyl Abietate",
  "Abitol",
  // Norsk
  "Kolofonium",
  "Disproporsjonert harpiks",
  "Gummiharpiks",
  "Treharpiks",
  "Furuharpiks",
  "Abietisk alkohol",
  "Abietylalkohol",
  "Metylabietatalkohol",
  "Tretjære",
  "Tallolje",
  "Abietinsyre",
  "Abietisk alkohol",
  "Metylabietat",
  "Furu harpiks",
  "Treharpiks",
  // EU
  " POLYESTER-41 ",
  " HYDROABIETYL ALCOHOL",
  "Phenanthrenemethanol",
  "dodecahydro-1,4a-dimethyl-7-(1-methylethyl)-",
  "Trialkylamin",
  "trialkanolamin",
  "DIMETHYL BEHENAMINE",
"  DIMETHYL BEHENAMINE",
"  DIBEHENYL METHYLAMINE",
"  DIMETHYL COCAMINE",
"  DIMETHYL HYDROGENATED TALLOWAMINE",
"  DIMETHYL LAURAMINE",
"  DIMETHYL LAURAMINE ISOSTEARATE",
"  DIMETHYL MYRISTAMINE",
"  DIMETHYL PALMITAMINE",
"  DIMETHYL STEARAMINE",
"  DIMETHYL SOYAMINE",
"  DIMETHYL TALLOWAMINE",
"  DI-TEA-OLEAMIDO PEG-2 SULFOSUCCINATE",
"  DI-TEA-PALMITOYL ASPARTATE",
"  LAURYL DIMETHYLAMINE CYCLOCARBOXYPROPYLOLEATE",
"  MAGNESIUM/TEA-COCO-SULFATE",
"  METHYL DICOCAMINE",
"  SODIUM/TEA-UNDECYLENOYL ALGINATE",
"  SODIUM/TEA-UNDECYLENOYL CARRAGEENAN",
"  SULFURIZED TEA-RICINOLEATE",
"  TEA-C10-15 ALKYL SULFATE",
"  TEA-C12-13 ALKYL SULFATE",
"  TEA-C12-14 ALKYL SULFATE",
"  TEA-C12-15 ALKYL SULFATE",
"  TEA-COCOATE",
"  TEA-COCOYL GLUTAMATE",
"  TEA-COCOYL HYDROLYZED COLLAGEN",
"  TEA-COCOYL SARCOSINATE",
"  TEA-EDTA",
"  TEA-LAUROYL GLUTAMATE",
"  TEA-HYDROCHLORIDE",
"  TEA-LAUROYL LACTYLATE",
"  TEA-LACTATE",
"  TEA-LAUROYL METHYLAMINOPROPIONATE",
"  TEA-LAURYL SULFATE",
"  TEA-MYRISTATE",
"  TEA-OLEATE",
"  TEA-PEG-3 COCAMIDE SULFATE",
"  TEA-PALMITATE",
"  TEA-PHENYLBENZIMIDAZOLE SULFONATE",
"  TEA-SALICYLATE",
"  TEA-SORBATE",
"  TEA-SULFATE",
"  TEA-STEARATE",
"  TEA-TALLATE",
"  TEA-UNDECYLENATE",
"  TEA-TRIDECYLBENZENESULFONATE",
"  TIPA-LAURETH SULFATE",
"  TRIETHANOLAMINE",
"  TRIISOPROPANOLAMINE",
"  TRILAURYLAMINE",
"  DI-TEA-COCAMIDE DIACETATE",
"  POLYURETHANE-17",
"  POLYURETHANE-18",
"  POLYURETHANE-19",
"  TIPA-ACRYLATES/ETHYLHEXYL ACRYLATE COPOLYMER",
"  TIPA-MYRISTATE",
"  POLYURETHANE-21",
"  TEA-ACRYLATES/ETHYLHEXYL ACRYLATE COPOLYMER",
"  TEA-ALGINATE",
"  TEA-C11-15 ALKYL SULFATE",
"  TEA-C12-13 PARETH-3 SULFATE",
"  TEA-C12-14 ALKYL PHOSPHATE",
"  TEA-C12-13 ALKYL PHOSPHATE",
"  TEA-COCAMIDE DIACETATE",
"  TEA-COCOYL ALANINATE",
"  TEA-COCOYL GLUTAMINATE",
"  TEA-COCOYL GLYCINATE",
"  TEA-DEXTRIN OCTENYLSUCCINATE",
"  TEA-DIETHANOLAMINOETHYL POLYISOBUTENYLSUCCINATE",
"  TEA-DIMETHICONE PEG-7 PHOSPHATE",
"  TEA-GLYCERYL DIMALEATE",
"  TEA-HYDROGENATED COCOATE",
"  TEA-HYDROGENATED TALLOWOYL GLUTAMATE",
"  TEA-LAURATE/MYRISTATE",
"  TEA-C11-15 PARETH SULFATE",
"  TEA-LAURETH-4 PHOSPHATE",
"  TEA-LAUROYL/MYRISTOYL ASPARTATE",
"  TEA-LAURYL PHOSPHATE",
"  DIMETHYL LAURAMINE DIMER DILINOLEATE",
"  TEA-PEG-50 HYDROGENATED CASTOR OIL SUCCINATE",
"  DIMETHYL LAURAMINE OLEATE",
"  DISTEARYLDIMETHYLAMINE DILINOLEATE",
"  SODIUM/TEA-UNDECYLENOYL COLLAGEN AMINO ACIDS",
"  SODIUM/TEA-UNDECYLENOYL HYDROLYZED COLLAGEN",
"  SODIUM/TEA-UNDECYLENOYL HYDROLYZED CORN PROTEIN",
"  SODIUM/TEA-UNDECYLENOYL HYDROLYZED WHEAT PROTEIN",
"  SODIUM/TEA-UNDECYLENOYL HYDROLYZED SOY PROTEIN",
"  SODIUM/TEA-LAUROYL COLLAGEN AMINO ACIDS",
"  SODIUM/TEA-LAUROYL HYDROLYZED COLLAGEN",
"  SODIUM/TEA-LAUROYL HYDROLYZED KERATIN",
"  SODIUM/TEA-LAUROYL KERATIN AMINO ACIDS",
"  TIPA-STEARATE",
"  TIPA-LAURYL SULFATE",
"  TEA-ABIETOYL HYDROLYZED COLLAGEN",
"  TEA-ACRYLATES/ACRYLONITROGENS COPOLYMER",
"  TEA-CANOLATE",
"  TEA-CARBOMER",
"  TEA-COCO-SULFATE",
"  TEA-COCOYL HYDROLYZED SOY PROTEIN",
"  TEA-DODECYLBENZENESULFONATE",
"  TEA-HYDROIODIDE",
"  TEA-ISOSTEARATE",
"  TEA-ISOSTEAROYL HYDROLYZED COLLAGEN",
"  TEA-LANETH-5 SULFATE",
"  TEA-LAURAMINOPROPIONATE",
"  TEA-LAURATE",
"  TEA-LAURETH SULFATE",
"  TEA-LAUROYL COLLAGEN AMINO ACIDS",
"  TEA-LAUROYL HYDROLYZED COLLAGEN",
"  TEA-LAUROYL KERATIN AMINO ACIDS",
"  TEA-LAUROYL SARCOSINATE",
"  TEA-MYRISTAMINOPROPIONATE",
"  TEA-OLEOYL HYDROLYZED COLLAGEN",
"  TEA-MYRISTOYL HYDROLYZED COLLAGEN",
"  TEA-OLEYL SULFATE",
"  TEA-OLEOYL SARCOSINATE",
"  TEA-PALM KERNEL SARCOSINATE",
"  TEA-PCA",
"  TEA-UNDECYLENOYL HYDROLYZED COLLAGEN",
"  TEA-ROSINATE",
"  TEA-C8-18 PERFLUOROALKYLETHYL PHOSPHATE",
"  HYDROXYETHYL ISOSTEARYLOXY ISOPROPANOLAMINE",
"  DIHYDROGENATED TALLOW METHYLAMINE",
"  BUTYL DIETHANOLAMINE",
"  TEA C14-17 ALKYL SEC SULFONATE",
"  SODIUM/TEA C12-13 PARETH-3 SULFATE",
"  DICOCODIMETHYLAMINE DILINOLEATE",
"  POLYURETHANE-46",
  // EU Norsk
  "Hydroabietyalkohol",
  "Fenanthrenmetanol",
  "Trialkylamin",
  "Trialkanolamin",
  "Dimetylbehenamin",
  "Dibehennylmetylamin",
  "Dimetylkokamin",
  "Dimetylhydrogenert talgamid",
  "Dimetyllauramin",
  "Dimetyllauraminisostearat",
  "Dimetylmyristamin",
  "Dimetylpalmitamin",
  "Dimetylstearamin",
  "Dimetylsoyaamin",
  "Dimetyltalgamin",
  "Lauryldimetylamin syklokarboksypropyloleat",
  "Magnesium/TEA-kokosulfat",
  "Metyl-dikokamin",
  "Natrium/TEA-undecylenoyl-alginat",
  "Natrium/TEA-undecylenoyl-karrageenan",
  "Svovelisert TEA-ricinoleat",
  "TEA-C10-15-alkylsulfat",
  "TEA-C12-13-alkylsulfat",
  "TEA-C12-14-alkylsulfat",
  "TEA-C12-15-alkylsulfat",
  "TEA-kokoat",
  "TEA-kokoylglutamat",
  "TEA-kokoylhydrolysert kollagen",
  "TEA-kokoylsarkosinat",
  "TEA-EDTA",
  "TEA-lauroylglutamat",
  "TEA-hydroklorid",
  "TEA-lauroyl-laktylat",
  "TEA-laktat",
  "TEA-lauroyl-metylaminopropionat",
  "TEA-laurylsulfat",
  "TEA-myristat",
  "TEA-oleat",
  "TEA-PEG-3-kokamid-sulfat",
  "TEA-palmitat",
  "TEA-fenylbenzimidazolsulfonat",
  "TEA-salisylat",
  "TEA-sorbat",
  "TEA-sulfat",
  "TEA-stearat",
  "TEA-tallat",
  "TEA-undecylenat",
  "TEA-tridecylbenzensulfonat",
  "TIPA-laurethsulfat",
  "Trietanolamin",
  "Triisopropanolamin",
  "Trilaurylamin",
  "Di-TEA-kokamid-diacetat",
  "Polyuretan-17",
  "Polyuretan-18",
  "Polyuretan-19",
  "TIPA-akrylater/etylheksyl-akrylat-kopolymer",
  "TIPA-myristat",
  "Polyuretan-21",
  "TEA-akrylater/etylheksyl-akrylat-kopolymer",
  "TEA-alginat",
  "TEA-C11-15-alkylsulfat",
  "TEA-C12-13-pareth-3-sulfat",
  "TEA-C12-14-alkylfosfat",
  "TEA-C12-13-alkylfosfat",
  "TEA-kokamid-diacetat",
  "TEA-kokoylalaninat",
  "TEA-kokoylglutaminat",
  "TEA-kokoylglycinat",
  "TEA-dextrin-oktenylsuksinat",
  "TEA-dietanoloaminetyl-polyisobutenylsuksinat",
  "TEA-dimetikon-PEG-7-fosfat",
  "TEA-glyseryldimaleat",
  "TEA-hydrogenert-kokoat",
  "TEA-hydrogenert-talgoylglutamat",
  "TEA-laurat/myristat",
  "TEA-C11-15-pareth-sulfat",
  "TEA-laureth-4-fosfat",
  "TEA-lauroyl/myristoyl-aspartat",
  "TEA-lauroylkollagenaminosyrer",
  "TEA-lauroylhydrolysert-kollagen",
  "TEA-lauroylkeratinaminosyrer",
  "TEA-lauroylsarkosinat",
  "TEA-myristaminopropionat",
  "TEA-oleoylhydrolysert-kollagen",
  "TEA-myristoylhydrolysert-kollagen",
  "TEA-oleylsulfat",
  "TEA-oleoylsarkosinat",
  "TEA-palmekernelsarkosinat",
  "TEA-PCA",
  "TEA-undecylenoylhydrolysert-kollagen",
  "TEA-rosinat",
  "TEA-C8-18-perfluoralkyletylfosfat",
  "Hydroksyetyl-isostearyloxy-isopropanolamin",
  "Dihydrogenerert-talgmetylamin",
  "Butyldiethanolamin",
  "TEA-C14-17-alkyl-sek-sulfonat",
  "Natrium/TEA-C12-13-pareth-3-sulfat",
  "Dikokodimetylamin-dilinoleat",
  "Polyuretan-46",
  // CAS
  " 8050-09-7 ",
  " 8050-26-8 ",
  " 65997-05-9 ",
  " 65997-06-0 ",
  " 242812-90-4 ",
  " 242812-90-4 ",
  " 666-84-2 ",
  "247-574-0 ",
  "	26266-77-3",
  " 8002-26-4 ",
  " 514-10-3 ",
  " 68153-38-8 ",
  " 68648-53-3 ",
  "8050-13-3 ",
  "8050-15-5",
  " 64365-17-9 ",
  " 65997-13-9 ",
  " 169590-84-5 ",
  "8050-31-5 ",
  "	65997-13-9 ",
  " 68186-14-1 ",
  " 61790-65-5 ",
  " 9010-69-9 ",
  " 83137-13-7 ",
  " 8050-09-7 ",
  " 65997-07-1 ",
  // EC
  " 500-163-2 ",
  "232-475-7",
  " 232-479-9 ",
  " 232-475-7 ",
  " 266-041-3 ",
  " 280-192-2 ",
  " 232-723-4 ",
  " 263-156-0 ",
  " 269-035-9 ",
  "	266-042-9 ",
  "232-482-5 ",
  " 266-042-9 ",
  " 264-848-5 ",
  " 232-476-2 ",
  " 271-996-4 ",
  " 268-884-2 ",
  " 232-304-6 ",
  " 208-178-3 ",
  "13393-93-6 ",
  "236-476-3 ",
  " 211-564-4 ",


  // 2-Hydroxyethylmethacrylate (H-010)
  "Hydroxyethylmethacrylate",
  "H-010",
  // Synonyms
  "glycol methacrylate",
  "glycol monomethacrylate",
  "Mhoromer",
  "heme-a",
  "Propenoic acid",
  "2-methyl,2-hydroxyethyl",
  "GMA",
  "Ethylene glycol methacrylate",
  "HEMA",
  "(methacryloyloxy)ethanol",
  // Norsk
  "Hydroksyetylmetakrylat",
  "Glykolmetakrylat",
  "Glykolmonometakrylat",
  "Propenosyre",
  "2-Metyl,2-hydroksyetyl",
  "Etylenglykolmetakrylat",
  "(Metakryloyloxy)etanol",
  // EU
  " POLYURETHANE-83 ",
  " POLYURETHANE-69 ",
  " METHACRYLOYLOXYETHYL CAPROATE PHOSPHATE ",
  " POLYURETHANE-86 ",
  " POLYACRYLATE-49 ",
  " POLYACRYLATE-44 ",
  " POLYURETHANE-88 ",
  " METHACRYLOYLOXYETHYL PHOSPHATE",
  " POLYURETHANE-90 ",
  " POLYURETHANE-51 ",
  " POLYACRYLATE-36 ",
  " POLYACRYLATE CROSSPOLYMER-15 ",
  " POLYACRYLATE-51 ",
  "Tetramethrin",
  " POLYURETHANE-104 ",
  " POLY(PENTYLENE/HEXAMETHYLENE CARBONATE)/IPDI COPOLYMER ",
  // EU Norsk
  "Metakryloyloxyetyl-kaproatfosfat",
  "Metakryloyloxyetylfosfat",
  "Tetrametrin",
  "Poly(pentyl/hexametylkarbonat)/IPDI-kopolymer",


  // Cobalt (C-017A)
  "Cobalt",
  "(C-017A)",
  // Synonyms
  "hexahydrate",
  "CCRIS 7729",
  // Norsk
  "Kobolt",
  "Hexahydrat",
  // EU
  "CI 77346",
  "Blue 28",
  "Blue Spinel",
  "GREEN 50 ",
  "Black 25",
  "CI 77332",
  // EU Norsk
  "Blå spinell",
  "Grønn 50",
  "Svart 25",
  // CAS
  " 7440-48-4 ",
  " 231-158-0 ",
  " 7646-79-9 ",
  " 10124-43-3 ",
  " 23384-69-2 ",
  " 105883-52-1 ",
  " 10141-05-6 ",
  " 513-79-1 ",
  " 1345-16-0 ",
  " 68186-85-6 ",
  " 71-48-7 ",
  " 12017-38-8 ",
  "68186-89-0 ",
  " 58591-45-0 ",
  " 12737-30-3 ",
  "68016-03-5",
  // EC
  " 231-589-4 ",
  " 233-334-2 ",
  " 233-402-1 ",
  " 208-169-4 ",
  " 310-193-6 ",
  " 200-755-8 ",
  " 234-618-9 ",
  " 442-750-5 ",
  " 269-051-6 ",
  " 261-346-8 ",
  " 620-395-9 ",
  "268-169-5 ",
  
  
  // warning labels for potential skin allergens
  "H317 - GENERIC WARNING LABEL",
  "R43 - GENERIC WARNING LABEL",

  // Generic 
  "Fragrance",
  "Perfume",
  "Aroma",
  "Duft",
  "Parfyme",

  //Discovered
  "Pine Oil",
]

export const allergensWithoutCodes = listOfAllergens.filter(allergen => /[a-z]+|[A-Z]+/.test(allergen))


export const minimalistAllergenList = [
  "Carba Mix",
  "MDBGN (Methyldibromo glutaronitrile)",
  "Toluenesulfonamide formaldehyde resin",
  "Colophony",
  "2-Hydroxyethylmethacrylate",
  "Cobalt",
  "2-Bromo-2-nitropropane-1,3-diol",
  
  "hexahydrate",
  "CCRIS 7729",
  "2-Bromo-2",
  "dibromoglutaronitrile",
  "bromomethyl glutaronitrile",
  "bromomethyl pentanedinitrile",
  "Dibromo dicyanobutane",
  "1,2-Dibromo-2,4-dicyanobutane",
  "Dibromodicyanobutane",
  "Merquat 2200",
  "Phenoxyethanol",
  "Tektamer 38",
  "Bromothalonil",
  "Euxyl K400",
  "Metacide 38",
  "Benzene sulfonamide",
  "4-methyl-polymer",
  "Mearlmaid TX-EPM-8-6",
  "Santolite MHP",
  "Santolite MS",
  "Tosylamide",
  "2-Nitro-2",
  "Bronidiol",
  "Bronocot",
  "Bronopol",
  "Bronosol",
  "Bronotak",
  "HSDB 7195",
  "Lexgard bronopol",
  "NSC 141021",
  "Onyxide 500",
  "nitrotrimethyleneglycol",
  "b-Bromo-b",
  "myacide",
  "bromo-2-nitro",
  "bromo-1-nitro",
  "nitro-2-bromo",
  "nitro-1-bromo",
  "Disproportionated rosin",
  "Disproportionated resin",
  "Gum resin",
  "Wood resin",
  "Pine resin",
  "Pine gum",
  "Wood Gum",
  "Colophony",
  "Abietic alcohol",
  "Abietyl alcohol",
  "Colophonium",
  "Rosin",
  "Tall oil",
  "Abietic acid",
  "Abietic Alcohol",
  "Methyl Abietate",
  "Abitol",
  "glycol methacrylate",
  "glycol monomethacrylate",
  "Mhoromer",
  "heme-a",
  "Propenoic acid",
  "2-methyl,2-hydroxyethyl",
  "GMA",
  "Ethylene glycol methacrylate",
  "HEMA",
  "(methacryloyloxy)ethanol",
  "Carbamate",
  "Diphenylguanidine",
  "DPG",
  "Noccel D",
  "Sanceler D",
  "Zinc Dibutyldithiocarbamate",
  "Butasan",
  "Butazate",
  "Butazin",
  "Butyl Zimate",
  "Zinc Deithydithiocarbamate",
  "ZDC",
  "ZBC",
  "Nocceler BZ",
  "Soxinol",
  "Etazin",
  "Ethasan",
  "Ethazate",
  "Ethyl Zimate",
  "Nocceler EZ",
  "zinc bis(diethyldithiocarbamate)",
  "bis(N,N-dibutyldithiocarbamato)zinc",
  "carbamic acid dibutyldithio",
  "zinc complex",
  "zinc bis(dibutyldithiocarbamate)",
  "Zincdiethyldithiocarbamate",
  "diethyldithiocarbamic acid zinc salt",
  
]